### ISSUE TITLE
Pedido de Contribuição

### ISSUE THREAD

**Issue by manuelhonoredesousa** [martygo/ao-tools#8]
Saudações irmão, acabei vendo o repositório e achei muito da hoje e estou com muitas ideias legais e queria saber se posso contribuir no projecto...

Ahhh, já ia me esquecendo, sou o Manuel de Sousa, (Mobile e Web Dev 😁 - Next.js e React Native)

**Comment by martygo** [comment]
Beleza, mano?

Nem precisa pedir mano, quanto mais contribuições, seja de qual natureza for, é sempre bem-vindo 🤗 e requisitada.

Mbora trabalhar mano.

**Comment by manuelhonoredesousa** [comment]
Seria bom se fizessem as issue do que estão trabalhando a fim de eu saber. E não haver redundâncias...

**Comment by martygo** [comment]
Feito mano. Atualmente só estou trabalhando numa única feature, já abri a issue.

Assim que pegares uma feature, é só abrir uma issue também mano.

**Comment by manuelhonoredesousa** [comment]
Está bem...

De uma olhada na minha Pull-Request e me dê um feedback **brow**

Fiz uma correção apenas...


https://github.com/martygo/ao-tools/pull/13/commits
